[project]
name = "bede-ml-toolkit"
version = "1.0.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dacite>=1.9.2",
    "pathlib>=1.0.1",
    "pytest>=8.4.2",
    "pyyaml>=6.0.3",
]

[project.optional-dependencies]
pytest = []

[dependency-groups]
dev = [
    "pytest-cov>=7.0.0",
]

[project.scripts]
ml-toolkit = "bede_containers:main"
install_ml-toolkit = "setup:create_toolkit_home"
install_apptainer = "setup:install_apptainer"

[build-system]
requires = ["uv_build>=0.8.23,<0.9.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
data = { data = "Data" }
module-name = ["bede_containers", "setup"]
