[pytest]
testpaths =tests
markers =
    unit: unit tests.
    CASTEP: Tests that require  an installation of CASTEP Note these are also very are slow to run.
    GPU: mark test as requiring a working GPU

addopts = -m "not CASTEP"